logger_topic_id:
  default: 863
allow_no_reason:
  default: true
max_length_raw:
  default: 1000
logger_topic_id_override_for_reviewable_type:
  default: "ReviewableUser=>863"
  type: list
skip_for_categories:
  default: ""
  type: list
  list_type: category
logger_topic_id_override_for_catrgories:
  default: "3=>863"
  type: list
hide_reviewable_details:
  default: false
hide_reviewable_user_email:
  default: false
hide_reviewable_user_fields:
  default: ""
  type: list